export type CQueueImport = {
  input_file_id?: number | null;
  url?: string | null;
  create_time?: string | null;
  post_url?: string | null;
  koc?: string | null;
  platform?: string | null;
  description?: string | null;
  file_url?: string | null;
  thumb_url?: string | null;
  tags?: string | null;
  transcript?: string | null;
  match_keywords?: string | null;
  comments?: string | null;
  is_detect_voice?: number | null;
  total_views?: number | null;
  total_likes?: number | null;
  total_shares?: number | null;
  total_comments?: number | null;
  total_saves?: number | null;
  koc_follower_count?: number | null;
  uploaded_time?: string | null;
  labels?: any | null;
  search_volume?: number | null;
  bid_price?: number | null;
  min_price?: number | null;
  max_price?: number | null;
  min_cpc?: number | null;
  max_cpc?: number | null;
  trend?: string | null;
  similar_keywords?: string | null;
  keyword?: string | null;
  keyword_search?: string | null;
  country?: string | null;
  confident_rate?: number | null;
  status?: number | null;
  page?: number | null;

  // trash params
  video?: any | null;
  author?: any | null;
  name?: string | null;
  title?: string | null;
  id?: string | null;
  desc?: string | null;
  post?: any | null;
  created_at?: any | null;
} | null;
